use me#3

diff --git a/.github/workflows/auto-pull.yml b/.github/workflows/auto-pull.yml
--- a/.github/workflows/auto-pull.yml
+++ b/.github/workflows/auto-pull.yml
@@ -20,9 +20,15 @@ jobs:
           repository: GraduationProjectSAMS/Workflows
           ref: main
 
-      - name: ls
+      - name: Setup SSH for Access
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         run: |
-          echo "inventory : $(cat inventory.ini)"
+          mkdir -p ~/.ssh
+          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+
+          # Extract IPs from the inventory.ini file and add them to known_hosts with error handling
           for host in $(grep -Eo '^[a-zA-Z0-9.-]+' inventory.ini); do
             echo "Adding $host to known_hosts"
             ssh-keyscan -H $host >> ~/.ssh/known_hosts 2>/dev/null || {
@@ -30,3 +36,46 @@ jobs:
               echo "$host" >> unresolved_hosts.txt
             }
           done
+
+      - name: Pull Latest Code on Servers
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+        run: |
+          unresolvedHost=$(cat unresolved_hosts.txt || echo "No unresolved hosts")
+
+          branchName=$(echo "$GITHUB_REF" | awk -F/ '{print $3}')
+          
+          while read -r line; do
+            # Extract the host and user from each line in the inventory.ini
+            host=$(echo "$line" | grep -oP '^[a-zA-Z0-9.-]+')
+            user=$(echo "$line" | grep -oP 'user=\K\w+')
+            dir=$(echo "$line" | grep -oP 'dir=\K\S+')
+            echo "Connecting to $user@$host"
+            if [ -n "$unresolvedHost" ] && grep -q "$host" unresolved_hosts.txt; then
+              echo "Skipping $user@$host due to unresolved host"
+              continue
+            fi
+
+            # Attempt SSH connection and execute commands
+            ssh -o "StrictHostKeyChecking=no" "$user@$host" "
+              echo 'Connected to $user@$host'
+              cd $dir &&
+              git stash --include-untracked &&
+              currentBranchName=\$(git rev-parse --abbrev-ref HEAD) &&
+              echo \"Current branch is \$currentBranchName\" &&
+              git fetch --all &&
+              git checkout $branchName &&
+              git reset --hard origin/$branchName &&
+          
+              # Run commands passed from the child workflow
+              ${{
+                inputs.commands
+              }} &&
+          
+              git checkout \$currentBranchName &&
+              git stash pop
+            " || echo "Error: Could not update code on $user@$host" &
+
+          done < <(grep -E '^[^\[#;]' inventory.ini)
+          wait
+          echo "Code pull process completed on all servers"
